# Generated by Django 3.0.3 on 2020-02-03 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationModel',
        ),
    ]
